config/routes.rb
Fulcrum::Application.routes.draw do

  get "story/new"
  get "locales" => "application#locales"

  resources :projects do
    resources :users, :only => [:index, :create, :destroy]
    resources :changesets, :only => [:index]
    resources :stories, :only => [:index, :create, :update, :destroy, :show] do
      resources :notes, :only => [:index, :create, :show, :destroy]
      collection do
        get :done
        get :in_progress
        get :backlog
        get :import
        post :import_upload
      end
      member do
        put :start
        put :finish
        put :deliver
        put :accept
        put :reject
      end
    end
  end

  devise_for :users, :controllers => { 
      :confirmations => "confirmations", 
      :registrations => "registrations"
    }

  if Rails.env.development?
    get 'testcard' => 'static#testcard'
  end

  root "projects#index"

end

app/views/notifications/accepted.text.erb
<%= @accepted_by.name %> has accepted the story '<%= @story.title %>'.

<%= project_url @story.project %>

app/views/notifications/delivered.text.erb
<%= @delivered_by.name %> has delivered your story '<%= @story.title %>'.

You can now review the story, and either accept or reject it.

<%= project_url @story.project %>

app/views/notifications/new_note.text.erb
<%= @note.user.name %> added the following comment to the story
"<%= @story.title %>":

<%= @note.note %>

app/views/notifications/rejected.text.erb
<%= @accepted_by.name %> has rejected the story '<%= @story.title %>'.

<%= project_url @story.project %>