config/routes.rb
Fulcrum::Application.routes.draw do

  get "story/new"
  get "locales" => "application#locales"

  resources :projects do
    resources :users, :only => [:index, :create, :destroy]
    resources :changesets, :only => [:index]
    resources :stories, :only => [:index, :create, :update, :destroy, :show] do
      resources :notes, :only => [:index, :create, :show, :destroy]
      collection do
        get :done
        get :in_progress
        get :backlog
        get :import
        post :import_upload
      end
      member do
        put :start
        put :finish
        put :deliver
        put :accept
        put :reject
      end
    end
  end

  devise_for :users, :controllers => { 
      :confirmations => "confirmations", 
      :registrations => "registrations"
    }

  if Rails.env.development?
    get 'testcard' => 'static#testcard'
  end

  root "projects#index"

end

app/models/project.rb
class Project < ActiveRecord::Base

  JSON_ATTRIBUTES = [
    "id", "iteration_length", "iteration_start_day", "start_date",
    "default_velocity"
  ]
  JSON_METHODS = ["last_changeset_id", "point_values"]

  # These are the valid point scalse for a project.  These represent
  # the set of valid points estimate values for a story in this project.
  POINT_SCALES = {
    'fibonacci'     => [0,1,2,3,5,8],
    'powers_of_two' => [0,1,2,4,8],
    'linear'        => [0,1,2,3,4,5],
  }
  validates_inclusion_of :point_scale, :in => POINT_SCALES.keys,
    :message => "%{value} is not a valid estimation scheme"

  ITERATION_LENGTH_RANGE = (1..4)
  validates_numericality_of :iteration_length,
    :greater_than_or_equal_to => ITERATION_LENGTH_RANGE.min,
    :less_than_or_equal_to => ITERATION_LENGTH_RANGE.max, :only_integer => true,
    :message => "must be between 1 and 4 weeks"

  validates_numericality_of :iteration_start_day,
    :greater_than_or_equal_to => 0, :less_than_or_equal_to => 6,
    :only_integer => true, :message => "must be an integer between 0 and 6"

  validates :name, :presence => true

  validates_numericality_of :default_velocity, :greater_than => 0,
                            :only_integer => true

  has_and_belongs_to_many :users, -> { uniq }

  accepts_nested_attributes_for :users, :reject_if => :all_blank

  has_many :stories, :dependent => :destroy do

    # Populates the stories collection from a CSV string.
    def from_csv(csv_string)

      # Eager load this so that we don't have to make multiple db calls when
      # searching for users by full name from the CSV.
      users = proxy_association.owner.users

      csv = CSV.parse(csv_string, :headers => true)
      csv.map do |row|
        row_attrs = row.to_hash
        story = create({
          :state        => row_attrs["Current State"].downcase,
          :title        => row_attrs["Story"],
          :story_type   => row_attrs["Story Type"].downcase,
          :requested_by => users.detect {|u| u.name == row["Requested By"]},
          :owned_by     => users.detect {|u| u.name == row["Owned By"]},
          :accepted_at  => row_attrs["Accepted at"],
          :estimate     => row_attrs["Estimate"],
          :labels       => row_attrs["Labels"],
          :description  => row_attrs["Description"]
        })

        # Generate notes for this story if any are present
        story.notes.from_csv_row(row)

        story
      end
    end

  end
  has_many :changesets, :dependent => :destroy

  attr_writer :suppress_notifications

  scope :with_stories_notes, -> { includes(stories: :notes) }

  def suppress_notifications
    @suppress_notifications || false
  end

  def to_s
    name
  end

  # Returns an array of the valid points values for this project
  def point_values
    POINT_SCALES[point_scale]
  end

  def last_changeset_id
    changesets.last && changesets.last.id
  end

  def as_json(options = {})
    super(:only => JSON_ATTRIBUTES, :methods => JSON_METHODS)
  end

  def csv_filename
    "#{name}-#{Time.now.strftime('%Y%m%d_%I%M')}.csv"
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  # GET /projects
  # GET /projects.xml
  def index
    @projects = current_user.projects
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = current_user.projects.find(params[:id])
    @story = @project.stories.build

    respond_to do |format|
      format.html # show.html.erb
      format.js   { render :json => @project }
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = current_user.projects.find(params[:id])
    @project.users.build
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = current_user.projects.build(allowed_params)
    @project.users << current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => t('projects.project was successfully created')) }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = current_user.projects.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(allowed_params)
        format.html { redirect_to(@project, :notice => t('projects.project was successfully updated')) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = current_user.projects.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end

  protected

  def allowed_params
    params.fetch(:project,{}).permit(:name, :point_scale, :default_velocity, :start_date, :iteration_start_day, :iteration_length)
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
  # Returns an array of valid project point scales suitable for
  # use in a select helper.
  def point_scale_options
    Project::POINT_SCALES.collect do |name,values|
      ["#{name.humanize} (#{values.join(',')})", name]
    end
  end

  # Returns an array of valid iteration length options suitable for use in
  # a select helper.
  def iteration_length_options
    (1..4).collect do |weeks|
      [I18n.t('n weeks', :count => weeks), weeks]
    end
  end

  # Returns an array of day name options suitable for use in
  # a select helper.  The values are 0 to 6, with 0 being Sunday.
  def day_name_options
    I18n.t('date.day_names').each_with_index.collect{|name,i| [name,i]}
  end
end

app/views/projects/_form.html.erb
<div class="form-wrapper">
<%= form_for(@project) do |f| %>
  <%= render 'shared/form_errors', :object => @project if @project.errors.any? %>

  <div class="field-wrapper">
    <%= f.label :name %>
    <div class="field"><%= f.text_field :name %></div>
  </div>

  <div class="field-wrapper">
    <%= f.label :point_scale %>
    <div class="field"><%= f.select :point_scale, point_scale_options %></div>
  </div>

  <div class="field-wrapper">
    <%= f.label :default_velocity %>
    <div class="field"><%= f.text_field :default_velocity, :length => 2, :size => 3 %></div>
  </div>

  <div class="field-wrapper date-wrapper">
    <%= f.label :start_date %>
    <div class="field"><%= f.date_select :start_date %></div>
  </div>

  <div class="field-wrapper">
    <%= f.label :iteration_start_day %>
    <div class="field"><%= f.select :iteration_start_day, day_name_options %></div>
  </div>

  <div class="field-wrapper">
    <%= f.label :iteration_length %>
    <div class="field"><%= f.select :iteration_length, iteration_length_options %></div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/projects/_nav.html.erb
<h1><%= project.name %></h1>

<%- if defined? show_column_toggles -%>
<div id="column-toggles"></div>
<%- end -%>

<%= link_to_unless_current Story.model_name.human(:count => 2), project_path(project) %> |
<%= link_to_unless_current User.model_name.human(:count => 2), project_users_path(project) %> |
<%= link_to_unless_current t('edit'), edit_project_path(project) %> |
<%= link_to_unless_current t('import'), import_project_stories_path(project) %> |
<%= link_to t('export'), project_stories_path(project, :format => :csv) %>

app/views/projects/edit.html.erb
<% content_for :title_bar do %>
  <%= render :partial => 'projects/nav', :locals => {:project => @project} %>
<% end %>
<h2><%= t('projects.edit project') %></h2>

<%= render 'form' %>

app/views/projects/index.html.erb
<% content_for :title_bar do %>
  <h1><%= t('.listing projects') %></h1>
<% end %>

<ul id="projects">
  <% @projects.each do |project| %>
    <li>
      <div class="project_options">
        <%= link_to t('edit'), edit_project_path(project) %>
        <%= link_to User.model_name.human(:count => 2), project_users_path(project) %>
        <%= link_to t('delete'), project,
          :data => {:confirm => t('.are you sure you want to delete this project')},
          :method => :delete %>
      </div>
      <h2><%= link_to project.name, project %></h2>
      <%= Project.human_attribute_name('started_at') %>:
      <%= project.start_date %>
      <br />
      <p>
      <%= t('.the iteration starts on x with length of x weeks',
            :day    => t('date.day_names')[project.iteration_start_day],
            :count  => project.iteration_length) %>
      </p>
    </li>
  <% end %>
</ul>

<%= link_to t('projects.new project'), new_project_path, :class => :button %>

app/views/projects/new.html.erb
<% content_for :title_bar do %>
  <h1><%= t('projects.new project') %></h1>
<% end %>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<%= javascript_tag "var AUTH_TOKEN = '#{form_authenticity_token}';" if protect_against_forgery? %>

<script type="text/javascript">
$(function() {
  window.md = new Markdown.Converter();

  var project = new Fulcrum.Project(<%= @project.to_json.html_safe %>);
  project.users.reset(<%= @project.users.to_json.html_safe %>);
  project.current_user = new Fulcrum.User(<%= current_user.to_json.html_safe %>);

  var doneColumn = new Fulcrum.ColumnView({
    id: 'done', name: '<%= t('.done') %>', el: $('td.done_column'), sortable: false
  }).render();
  $('#column-toggles').append(
    new Fulcrum.ColumnVisibilityButtonView({columnView: doneColumn}).render().el
  );

  var inProgressColumn = new Fulcrum.ColumnView({
    id: 'in_progress', name: '<%= t('.in_progress') %>', el: $('td.in_progress_column'),
    sortable: true
  }).render();
  $('#column-toggles').append(
    new Fulcrum.ColumnVisibilityButtonView({columnView: inProgressColumn}).render().el
  );

  var backlogColumn = new Fulcrum.ColumnView({
    id: 'backlog', name: '<%= t('.backlog') %>', el: $('td.backlog_column'), sortable: true
  }).render();
  $('#column-toggles').append(
    new Fulcrum.ColumnVisibilityButtonView({columnView: backlogColumn}).render().el
  );

  var chillyBinColumn = new Fulcrum.ColumnView({
    id: 'chilly_bin', name: '<%= t('.icebox') %>', el: $('td.chilly_bin_column'),
    sortable: true
  }).render();
  $('#column-toggles').append(
    new Fulcrum.ColumnVisibilityButtonView({columnView: chillyBinColumn, elementId: 'chilly_bin'}).render().el
  );

  // FIXME Move to view
  // Connect up drag and drop behaviour
  $('#backlog').sortable('option', 'connectWith', '#chilly_bin,#in_progress');
  $('#chilly_bin').sortable('option', 'connectWith', '#backlog,#in_progress');
  $('#in_progress').sortable('option', 'connectWith', '#backlog,#chilly_bin');

  window.projectView = new Fulcrum.ProjectView({model: project});
  window.projectView.velocityView = new Fulcrum.ProjectVelocityView({
    model: project, el: $('#velocity')
  });
  window.projectView.scaleToViewport();
  $(window).resize(projectView.scaleToViewport);

  setInterval(function() {
   window.projectView.model.fetch();
  }, 5000);

  <% if notice %>
    window.projectView.notice({
      title: 'Notice', text: '<%= notice %>',
      image: '<%= image_path('dialog-information.png') %>'
    });
  <% end %>

  <% if alert %>
    window.projectView.notice({
      title: 'Alert', text: '<%= alert %>', sticky: true,
      image: '<%= image_path('dialog-warning.png') %>'
    });
  <% end %>
});
</script>

<% content_for :title_bar do %>
  <div id="velocity" class="velocity"></div>
  <%= render :partial => 'projects/nav',
             :locals => {:project => @project, :show_column_toggles => true} %>
             | <a id="add_story" href="#"><%= t('add story') %></a>
<% end %>

<table class="stories" width="100%">
  <tbody>
    <tr>
    <% if !Fulcrum::Application.config.fulcrum.column_order or Fulcrum::Application.config.fulcrum.column_order != 'progress_to_right' %>
      <td class="done_column" style="width: 25%"></td>
      <td class="in_progress_column" style="width: 25%"></td>
      <td class="backlog_column" style="width: 25%"></td>
      <td class="chilly_bin_column" style="width: 25%"></td>
    <% elsif Fulcrum::Application.config.fulcrum.column_order == 'progress_to_right' %>
      <td class="chilly_bin_column" style="width: 25%"></td>
      <td class="backlog_column" style="width: 25%"></td>
      <td class="in_progress_column" style="width: 25%"></td>
      <td class="done_column" style="width: 25%"></td>
    <% end %>
    </tr>
  </tbody>
</table>

<div class="loading_screen">
  <div class="spinner">
    <span class="icons-spinner"></span>
  </div>
</div>